# gitleaks.toml
# Configuration file for Gitleaks v8.28.0

[[rules]]
id = "generic-secret"
description = "Generic Secret (password, secret, API key)"
regex = '''(?i)(secret|password|api[_-]?key)[=:]\s*['"][A-Za-z0-9]{8,}['"]'''
tags = ["secret"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws","secret"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws_secret_access_key.*['"][0-9a-zA-Z/+]{40}['"]'''
tags = ["aws","secret"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[0-9a-zA-Z]{36,255}'''
tags = ["github","secret"]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{24,32}'''
tags = ["slack","secret"]
